### PR TITLE
CAM-10278 - Rest controller for starting process is added

### PR DESCRIPTION
**Pull request by hamedmirzaei**
In _spring-boot-starter.example-webapp_ module, I have added a rest controller to support starting the processes through _Http.GET_ request. Also, I have added _Lombok_ library to use its logging mechanism.

### CODE REVIEW

**Comment by marstamm** [comment]
Hi @hamedmirzaei ,

Thanks for raising this. I created https://app.camunda.com/jira/browse/CAM-10278 for it.
We will look into it and come back to you shortly.

Best,
Martin

**Comment by ThorbenLindhauer** [comment]
Hi @hamedmirzaei,

We are currently busy with finishing the 7.11 release, so it may take a little longer until we can review your PR.

Cheers,
Thorben

**Comment by koevskinikola** [comment]
Hi @hamedmirzaei,

Sorry for the long delay. We just finished releasing version 7.11 of the platform.

This looks like a great addition to the example! However, I found some issues that I think should be corrected:
1. The examples are intended to introduce a user/developer to the platform, so they are meant to be simple and easy. For this reason, I would avoid using Lombok so that developers unfamiliar with it don't get confused.
2. The `ProcessController` class should be covered by a test that asserts that a HTTP Get call instantiates a Process Instance. This way we will know if something breaks in future versions.

Cheers,
Nikola

**Comment by hamedmirzaei** [comment]
Hi @koevskinikola,

As you've requested, _Lombok_ has been removed and a _Test_ has been generated for the _ProcessController_ class. All changes had been commited.

Thanks,
Hamed Mirzaei

**Comment by koevskinikola** [comment]
Hi @hamedmirzaei,

Thank you for the adjustments. I just manually tested the feature you provided and I saw that the `UserTask` in the Process Instance is automatically completed:
https://github.com/camunda/camunda-bpm-examples/blob/42ff2f0d5d115ac1079ec43243044c35390f218b/spring-boot-starter/example-webapp/src/main/java/org/camunda/bpm/spring/boot/example/webapp/controller/ProcessController.java#L32 

What would be the gain of doing this since Historic data can't be viewed in the CE version of the webapps? This way, the whole Process Instance is completed, and the user wouldn't notice any changes.

Best,
Nikola

**Comment by hamedmirzaei** [comment]
Hi @koevskinikola,

Couple of years ago when I was a junior and tried to delve into new technologies, I've always had this problem that how can I have all the required classes to run a simple hello world. By adding this Rest controller I tried to help juniors on what is necessary and enough to make this run.

Regards,
Hamed Mirzaei

**Comment by koevskinikola** [comment]
Hi @hamedmirzaei,

Thank you for the explanation, it's a very valid point. But I think you misunderstood me. The point of the `Spring Boot Web application with Camunda Webapps` example is to show how users can configure the Camunda Process Engine and Camunda Webapps with our Spring Boot Starter. Through the Starter, we also provide the Engine Rest API which can be used to start Process Instances.

With you contribution, when a user sees an implementation for an endpoint to start a Process Instance and then, the Process Instance is not even available through the Webapps interface might be confusing.

This example: https://github.com/camunda/camunda-bpm-examples/tree/master/deployment/spring-boot is a much better place for your contribution. It shows how to bootstrap the Camunda Process Engine with Spring Boot, so it makes a lot of sense to also provide an example on how to implement a Rest API endpoint with Spring Boot that can start a Process Instance.

Would you be willing to move your code there?

Sorry for the delayed analysis, I just noticed the `taskService.complete(task.getId()); ` and with it, the contribution doesn't fit in this example.

Best,
Nikola

**Comment by hamedmirzaei** [comment]
Hi @koevskinikola,

I've got your point and now I am agree with you about removing this contribution to the mentioned example. I will do it soon.

Thanks,
Hamed Mirzaei

**Comment by koevskinikola** [comment]
Hi @hamedmirzaei,

I will close this PR until you decide to reopen it and push your changes.

Best,
Nikola

**Pull request closed without merging**
