### PR TITLE
chore(examples): add spring soap example

### PR DESCRIPTION
**Pull request by skjolber**
See issue CAM-4439

### CODE REVIEW

**Comment by saig0** [comment]
Hi Thomas,

thank you for your pull request.

Your example shows the usage of a soap webservice with a cxf generated client in a spring application. I think the most important part is the cxf webservice client. So I prefer rename the example to "SOAP CXF Client Example" or something like that. The project folder should also rename to "soap-cxf-service" so that it is near to the other soap example. Maybe you can write one sentence to difference to the other soap example.

And please add your example to the main README.md page.

Greetings,
Philipp

**Comment by skjolber** [comment]
Thanks for the feedback, will make adjustments.

**Comment by skjolber** [comment]
See updated commit (the rebase approach seems to have deleted some of the comments).

**Comment by skjolber** [comment]
By the way, if I use the spin dependency 'all', the unit test fails. The problem is caused by the 'response' JAXB-annotated object being automagically assigned the type "application/json" type. I am even able to make eclipse pass the junit test while the maven build is failing. 

So I am guessing there is no 'ranking' mechanism for autodetecting the nature of Java objects? When both JSON and XML spin are present in a project, I would assume that JAXB-annotated objects were given application/xml and Jackson-annotated object were given application/json.

**Comment by saig0** [comment]
Hi Thomas,

I merged your branch into master.

Your guess is right. If you have both xml and json spin datatypes imported and the variable is untyped (as in your example) and there is no default format, then the serialization format is non-deterministic xml or json. See [1](http://docs.camunda.org/7.3/guides/user-guide/#data-formats-xml-json-other-xml-serializing-process-variables)
Feel free to create an issue or provide a pull request.

Greetings,
Philipp

**Pull request merged**
