### PR TITLE
Cockpit JS only plugin for searching process by ID

### PR DESCRIPTION
**Pull request by ruslantagirov**
Hi. I made a simple JS only plugin for Cockpit Processes dashboard.
It allows to enter process ID and just redirects user to process detail page.
It is useful for searching a process when you have dozens of processese and deployments in Cockpit.

This is my first attempt on making something on Angular ever and my first web plugin as well.

### CODE REVIEW

**Comment by tasso94** [comment]
Hi Ruslan,

thanks for your contribution. 👍 

I will review your Cockpit Plugin and come back to you shortly.

Cheers,
Tassilo

**Comment by ruslantagirov** [comment]
Added toggle section as in original plugins and some fixes. Seems that's it.

**Comment by tasso94** [comment]
Hey Ruslan,

thank you for your contribution.

I adjusted your example slightly and merged it with the master branch.

Cheers,
Tassilo

**Comment by ruslantagirov** [comment]
Thanks!

**Pull request closed without merging**
