### PR TITLE
CAM-11753: Fix the interceptor registration in Camunda BPM examples

### PR DESCRIPTION
**Pull request by mbabic511**
Fix for small c/p error

### CODE REVIEW

**Comment by mboskamp** [comment]
Hi @mbabic511,

thanks for fixing this. Nice catch! I reviewed the change and it looks good.
As this is the first time you contribute to one of our repositories, we require you to sign the CLA linked in this pull request. This is a one-time thing. You don't need to do it again for future contributions.

I am happy to merge your contribution once the CLA is signed. :)
Cheers,
Miklas

**Comment by mboskamp** [comment]
Hey @mbabic511,

I haven't heard back from you in a while now. Please let me know by the end of this week if you want to proceed with this. Otherwise I will close the PR.

Cheers and have a nice week.
Miklas

**Comment by mbabic511** [comment]
Good morning Miklas,

apologies for not getting back to you yet - I needed to check with my
manager whether it is ok for me to sign the CLA and still didn't get the
response (I just pinged him :-) ).
I will let you know by end of this week for sure.

Kind regards,
Martin

**Comment by mbabic511** [comment]
Good morning Miklas,

I signed the CLA, so I think we are good to go. 👍 

Kind regards,
Martin

**Comment by mboskamp** [comment]
Hey Martin,
thanks again for the contribution. I have merged your change to the master branch.
Enjoy the rest of your week. :)

Best,
Miklas

**Pull request merged**
