### PR TITLE
CAM-12425: Issue with embedded:app - missing dependencies

### PR DESCRIPTION
**Pull request by PeterWhittaker**
Please see the note/issue I added, there is missing information in the README.md; it may simply be out of date with changes made to the libraries over the last few years.

### CODE REVIEW

**Comment by yanavasileva** [comment]
Hello @PeterWhittaker,

Thank you for reaching out to us with this.
In case you find issues with any of our products or examples you can create a ticket in our issue tracker: https://jira.camunda.com/secure/CreateIssue.jspa
or ask in our user forum by creating a new topic: https://forum.camunda.org/

And back to the reported issue, could you please let us know with which Camunda version you tried out the example?

Best regards,
Yana

**Comment by PeterWhittaker** [comment]
@yanavasileva 
> And back to the reported issue, could you please let us know with which Camunda version you tried out the example?

7.12

**Comment by PeterWhittaker** [comment]
@yanavasileva Please let me know if this is sufficient: https://jira.camunda.com/browse/CAM-12425

**Comment by yanavasileva** [comment]
Hi @PeterWhittaker,

Thank you for creating the ticket, it will help to track the issue better.

Just to be sure that the correct example if used, could you please follow the example instructions here:
https://github.com/camunda/camunda-bpm-examples/blob/7.12/sdk-js/browser-forms-angular/

Meantime I will try to reproduce the issue on my side as well.

Best regards,
Yana

**Comment by PeterWhittaker** [comment]
@yanavasileva 
> Just to be sure that the correct example if used, could you please follow the example instructions here:
> https://github.com/camunda/camunda-bpm-examples/blob/7.12/sdk-js/browser-forms-angular/

Those are the exact instructions I followed: That README.md is the one I reference in the issue and is also the one for which I created this PR.

**Comment by yanavasileva** [comment]
I am closing this in benefit of https://jira.camunda.com/browse/CAM-12425 where I will continue the communication.

**Pull request closed without merging**
